#!/bin/bash

# ensure user has installed aws cli and it's on path
# using shell built-in: "command" instead of "which"
command -v aws > /dev/null 2>&1 || { echo "AWS CLI not installed or not on path. Install and try again." >&2; exit 1; }

commandType=$1
artifactsPath=~/aws-automate-ec2-artifacts

# command input checking
if ! [[ "$commandType" = "configure"          \
              || "$commandType" = "launch"    \
              || "$commandType" = "terminate" \
              || "$commandType" = "connect"   \
              || "$commandType" = "status" ]]; then
    echo "usage: aws-ec2-automate configure|launch|terminate|connect|status"
    exit
fi

# configure
configFilePath=${artifactsPath}/config.cfg
if [[ "$commandType" = "configure" ]]; then
    if ! [[ -f "$configFilePath" ]]; then
        mkdir -p $artifactsPath && touch $configFilePath
    fi
    read -p 'image_id: ' imageId
    read -p 'instance_type: ' instanceType
    read -p 'key_name: ' keyName
    echo "image_id:${imageId}:instance_type:${instanceType}:key_name:${keyName}" > ${configFilePath}
    exit
fi

# ensure user has ran configure
if ! [[ -f "$configFilePath" ]]; then
    echo "run \"aws-ec2-automate configure\" first"
    exit
fi

# launch
instanceConfigFilePath=${artifactsPath}/instance_config.cfg
if [[ "$commandType" = "launch" ]]; then
    # if instance already running, report instance-id and public ip address
    if [[ -f "$instanceConfigFilePath" ]]; then
	echo "an instance is already running. see below for details:"
	cat $instanceConfigFilePath
	exit
    fi   

    # if instance isn't running, launch one.
    # write instance.cfg with instance information
    while IFS=: read imageId imageIdVal instanceType instanceTypeVal keyName keyNameVal; do
	if ! [[ "$imageId" = "image_id" && "$instanceType" = "instance_type" && "$keyName" = "key_name"  ]]; then
	    echo "config file corrupted, please run \"aws-ec2-automate configure\" again"
	    exit
	fi

	logFileName="launch_log.json"
	logFilePath=${artifactsPath}/${logFileName}

	aws ec2 run-instances                \
	    --image-id $imageIdVal           \
	    --instance-type $instanceTypeVal \
	    --key-name ${keyNameVal}         \
	    --count 1 > ${logFilePath}
	
	instanceIdVal="$(cat "$logFilePath" | grep InstanceId | cut -d '"' -f4)"
        publicIpAddress="$(aws ec2 describe-instances --instance-ids $instanceIdVal | \
                                             grep PublicIpAddress | cut -d '"' -f4)"
	
	echo "instance_id:${instanceIdVal}:public_ip:${publicIpAddress}" > ${instanceConfigFilePath}
    done < $configFilePath
        
    exit
fi

# terminate
if [[ "$commandType" = "terminate" ]]; then
    # ensure instance exists to be terminated
    if ! [[ -f "$instanceConfigFilePath" ]]; then
	echo "no instance is running to be terminated"	
	exit
    fi   
    
    # terminate instance
    while IFS=: read instanceId instanceIdVal publicIp publicIpVal; do
	if ! [[ "$instanceId" = "instance_id"  ]]; then
	    echo "instance config file corrupted, please terminate the instance manually"
	    exit
	fi
	aws ec2 terminate-instances --instance-ids $instanceIdVal

	# delete instance config file
	rm -f $instanceConfigFilePath
    done < $instanceConfigFilePath
    
    exit
fi

# connect
if [[ "$commandType" = "connect" ]]; then
    # ensure instance is running to be connected to
    if ! [[ -f "$instanceConfigFilePath" ]]; then
	echo "no instance is running to be connected to"	
	exit
    fi

    # connect via ssh
    while IFS=: read imageId imageIdVal instanceType instanceTypeVal keyName keyNameVal; do
	if ! [[ "$imageId" = "image_id" && "$instanceType" = "instance_type" && "$keyName" = "key_name"  ]]; then
	    echo "config file corrupted, please run \"aws-ec2-automate configure\" again"
	    exit
	fi

	while IFS=: read instanceId instanceIdVal publicIp publicIpVal; do
	    if ! [[ "$publicIp" = "public_ip"  ]]; then
		echo "instance config file corrupted, please connect to the instance manually"
		exit
	    fi

	    # now that we have keyname and public ip, start the ssh connection
	    # todo: consider removing hardcoded values e.g. "ubuntu"
	    # this is not working currently: "Pseudo-terminal will not be allocated because stdin is not a terminal."
	    # tried -tt but that halts the terminal once logged in.
	    # for now, echo the ssh command to enter manually
	    # or do this: $(./aws-ec2-automate connect) on the command line
	    echo "ssh -i ~/.ssh/${keyNameVal}.pem ubuntu@${publicIpVal}"
	done < $instanceConfigFilePath

    done < $configFilePath

    exit
fi

# status
if [[ "$commandType" = "status" ]]; then
    echo "ec2 config: "$(cat $configFilePath)""
    if [[ -f "$instanceConfigFilePath" ]]; then
	echo "instance information: "$(cat $instanceConfigFilePath)""
    else
	echo "no instance running currently"
    fi   

    exit
fi

exit 0
